student:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: student_employment
    username: root
    password: 123456
  redis:
    database: 2
    host: localhost
    password: 123456
    port: 6379
  alioss:
    endpint:
    access-key-id:
    access-key-secret:
    bucket-name: